### ISSUE TITLE
Compatibility with TYPO3 11.5 LTS

### ISSUE THREAD

**Issue by Patta** [studiomitte/redirect2trailingslash#3]
A compatibility release for TYPO3 11.5 LTS would be great. Thanks

**Comment by Patta** [comment]
Hi @georgringer is there any plan to update this helpful extension for TYPO3 11 or is there a better way to achieve the redirect to the trailing slash in TYPO3 11 today? Thanks for your feedback.

**Comment by georgringer** [comment]
I can take a look at it next week, shouldn't be hard

**Comment by Patta** [comment]
@georgringer just a friendly reminder, cheers
