### ISSUE TITLE
Urls with Parameter will not work

### ISSUE THREAD

**Issue by ohm-meter** [studiomitte/redirect2trailingslash#5]
Hi,

Urls with Parmeter like:
`domain.dev/sideurl?tx_iklq_voucherform%5Baction%5D=findLocationByZip&amp;tx_iklq_voucherform%5Bcontroller%5D=Voucher&amp;type=25183&amp;cHash=145c6b47456e110d8d913de441838c9e`
Should not be redirected.

Cheers Oliver

**Comment by georgringer** [comment]
is there a reason why not?

**Comment by ohm-meter** [comment]
The Problem was if i use JS Ajax Calls, wich are build in our application will break on that.
I think links with Parameter `type` should not be redirected.
But you can close this issue
